### PR TITLE
New Feature

### PR DESCRIPTION
**Pull request by ShennieWu**
Add a new Python Script

### CODE REVIEW

**Comment by PHANTOMS0308** [comment]
Shennie, I love your idea. But would you use JavaScript instead of Python?

**Comment by ShennieWu** [comment]
Rewritten Python into  JavaScript, let me know what else I can do?

**Comment by PHANTOMS0308** [comment]
It's all good, I will merge it rn, thanks Shennie

**Comment by PHANTOMS0308** [comment]
Would you recheck Feature #1 ?

**Comment by PHANTOMS0308** [comment]
Well, I gave you three options
- [] Fuck yourself
- [X] Suck my Dick
- [] Apologize with your body

**Comment by ShennieWu** [comment]
Perhaps we should use Python?

```python
def fucker(name):
  print('Fuck you ' + name)
```

**Comment by PHANTOMS0308** [comment]
> Perhaps we should use Python?

Are you insane?
Look at how clean is this JS implementation...

```javascript
function fucker(name) {
  console.log('Fuck you ' + name);
}
```

**Comment by ShennieWu** [comment]
😂 你是智障吧
karatan

**Comment by PHANTOMS0308** [comment]
1. 第一，去死 
2. 第二，操你妈
3. 第三，你傻逼吧

**Comment by PHANTOMS0308** [comment]
@ShennieWu  Fuck yoy

**Pull request merged**
